# Generated by Django 5.0.7 on 2024-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('sumber_buku', models.CharField(max_length=100)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
