# Generated by Django 5.0.7 on 2024-08-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus_app', '0003_delete_perpusappmasterbuku_alter_masterbuku_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterbuku',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mastersumberbuku',
            options={'managed': False},
        ),
    ]
