# Generated by Django 5.0.7 on 2024-08-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus_app', '0004_alter_masterbuku_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterbuku',
            table='master_buku',
        ),
    ]
