# Generated by Django 5.0.7 on 2024-08-05 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus_app', '0005_alter_masterbuku_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterbuku',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mastersumberbuku',
            options={'managed': True},
        ),
    ]
