# Generated by Django 5.0.7 on 2024-08-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus_app', '0006_alter_masterbuku_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_member', models.CharField(blank=True, max_length=256, null=True)),
                ('jenis_identitas', models.SmallIntegerField(blank=True, null=True)),
                ('no_identitas', models.CharField(blank=True, max_length=256, null=True)),
                ('nama', models.CharField(blank=True, max_length=256, null=True)),
                ('alamat_ktp', models.CharField(blank=True, max_length=256, null=True)),
                ('domisili', models.CharField(blank=True, max_length=256, null=True)),
                ('status_aktif', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'master_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaksiKunjungan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jenis_tansaksi', models.SmallIntegerField(blank=True, null=True)),
                ('tgl_transaksi', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('no_transaksi', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'transaksi_kunjungan',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='masterbuku',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mastersumberbuku',
            options={'managed': False},
        ),
    ]
