# Generated by Django 5.0.7 on 2024-08-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpus_app', '0007_mastermember_transaksikunjungan_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mastersumberbuku',
            table=None,
        ),
    ]
